services:
  - type: web
    name: flights-tracking-backend
    runtime: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    autoDeploy: true
    dockerfilePath: Dockerfile
    healthCheckPath: api/healthz
    envVars:
      - key: REACT_APP_HOST
        value: 'https://flights-tracking-frontend.onrender.com'
    buildFilter:
      branches:
        - main
      ignoredPaths:
        - ./README.md
    rootDir: backend

  - type: web
    name: flights-tracking-frontend
    runtime: static
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: 'https://flights-tracking-backend.onrender.com/api'
    buildFilter:
      branches:
        - main
      ignoredPaths:
        - ./README.md
    rootDir: frontend
