services:
  - type: web
    name: flights-tracking-backend
    runtime: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'uvicorn app.main:app --host 0.0.0.0 --port 8000'
    autoDeploy: true
    dockerfilePath: Dockerfile
    healthCheckPath: api/healthz
    envVars:
      - key: REACT_APP_HOST
        value: 'https://flights-tracking-frontend.onrender.com'
